from setuptools import setup

setup(
    name='aircraft-radar',
    version='1.0',
    description='A tkinter GUI which displays a radar of aircraft in a specified region using data pulled from the OpenSky Network API.',
    url='https://github.com/jmitchell-99/aircraft-radar',
    author='jmitchell-99',
    author_email='joemitchell091@gmail.com',
    packages=['aircraft-radar'],
    install_requires=[
        'basemap>=1.3.3',
        'basemap-data>=1.3.2',
        'certifi>=2022.5.18.1',
        'charset-normalizer>=2.0.12',
        'cycler>=0.11.0',
        'fonttools>=4.33.3',
        'idna>=3.3',
        'kiwisolver>=1.4.2',
        'matplotlib>=3.5.2',
        'numpy>=1.22.4',
        'packaging>=21.3',
        'pandas>=1.4.2',
        'Pillow>=9.1.1',
        'pyparsing>=3.0.9',
        'pyproj>=3.3.1',
        'pyshp>=2.1.3',
        'python-dateutil>=2.8.2',
        'pytz>=2022.1',
        'requests>=2.27.1',
        'scipy>=1.8.1',
        'six>=1.16.0',
        'urllib3>=1.26.9',
    ],
)
